apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
data:
  SPRING_APPLICATION_JSON: |
    {
      "spring": {
        "profiles": {
          "active": "prod"
        },
        "data": {
          "redis": {
            "host": "redis-master.default.svc.cluster.local",
            "port": 6379,
            "database": 0,
            "connect-timeout": 1000,
            "command-timeout": 5000,
            "batch-size": 1000
          }
        },
        "datasource": {
          "url": "jdbc:mysql://mysql-headless.mysql.svc.cluster.local:3306/api-server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8"
        },
        "elasticsearch": {
          "uris": "http://elasticsearch-master.default.svc.cluster.local:9200"
        }
      }
    }
  SPRING_BATCH_APPLICATION_JSON: |
    {
      "spring": {
        "profiles": {
          "active": "prod"
        },
        "batch": {
          "job": {
            "name": "FINANCIAL_COMPANY_SYNC_JOB"
          }
        },
        "datasource": {
          "url": "jdbc:mysql://mysql-headless.mysql.svc.cluster.local:3306/api-server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8"
        },
        "elasticsearch": {
          "uris": "http://elasticsearch-master.default.svc.cluster.local:9200"
        }
      }
    }
