apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
data:
  SPRING_APPLICATION_JSON: |
    {
      "spring": {
        "profiles": {
          "active": "prod"
        },
        "datasource": {
          "url": "jdbc:mysql://local-mysql-headless.local-mysql.svc.cluster.local:3306/api-server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8"
        }
      }
    }
  SPRING_BATCH_APPLICATION_JSON: |
    {
      "spring": {
        "profiles": {
          "active": "prod"
        },
        "batch": {
          "job": {
            "name": "FINANCIAL_COMPANY_SYNC_JOB"
          }
        },
        "datasource": {
          "url": "jdbc:mysql://local-mysql-headless.local-mysql.svc.cluster.local:3306/api-server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8"
        }
      }
    }